name: Fetch CNN JSON Every 2 Minutes

on:
  schedule:
    - cron: "*/2 * * * *"  # Her iki dakikada bir çalışır
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  fetch-json:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: Python Kurulumu
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip
          pip install requests

      - name: JSON Verisini Al ve Kaydet
        run: |
          python3 cnn_json_fetcher.py

      - name: Dosyayı GitHub'a Yükle
  env:
    GH_PAT: ${{ secrets.GH_PAT }}
  run: |
    git config --global user.name "CNN JSON Bot"
    git config --global user.email "example@example.com"
    git remote set-url origin https://x-access-token:${GH_PAT}@github.com/<kullanıcı_adı>/<depo_adı>.git
    git add veri.json
    git commit -m "veri.json dosyası güncellendi"
    git push
